load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

kernel_module(
    name = "px4_drv",
    outs = ["px4_drv.ko"],
    kernel_build = "//common:kernel_x86_64",
    makefile = [":Makefile"],
    srcs = glob([
        "driver/*.c",
        "driver/*.h",
        "include/**/*.h",
    ]) + [
        "Kbuild",
        "Makefile",
    ],
    visibility = ["//visibility:public"],
)
